import Mathlib

open scoped ArithmeticFunction.Moebius BigOperators

noncomputable section

namespace RHLean.Arithmetic

/-- The initial number field before the formal seed is applied. -/
def primeWheelZeroField : ℕ → ℤ := fun _ => 0

/-- The formal period-one seed.  Every site is provisionally assigned `-1`. -/
def primeWheelSeedField : ℕ → ℤ := fun _ => -1

/-- The local square-sensitive prime comb.

A first-power hit flips the sign, a square hit kills the site, and a miss leaves
it unchanged. -/
def localPrimeComb (p n : ℕ) : ℤ :=
  if p ^ 2 ∣ n then 0 else if p ∣ n then -1 else 1

/-- Pointwise action of one genuine prime operator. -/
def primeCombOperator (p : ℕ) (f : ℕ → ℤ) : ℕ → ℤ :=
  fun n => localPrimeComb p n * f n

@[simp] theorem primeWheelZeroField_apply (n : ℕ) :
    primeWheelZeroField n = 0 := rfl

@[simp] theorem primeWheelSeedField_apply (n : ℕ) :
    primeWheelSeedField n = -1 := rfl

/-- Distinct prime operators commute because both act pointwise by scalar
multiplication. -/
theorem primeCombOperator_comm (p q : ℕ) (f : ℕ → ℤ) :
    primeCombOperator p (primeCombOperator q f) =
      primeCombOperator q (primeCombOperator p f) := by
  funext n
  simp only [primeCombOperator]
  ring

/-- Raw seeded field generated by a finite set of prime coordinates. -/
def seededPrimeComb (S : Finset ℕ) (n : ℕ) : ℤ :=
  -∏ p ∈ S, localPrimeComb p n

/-- A site is fully smooth relative to the selected prime coordinates when it is
squarefree and every prime factor belongs to the coordinate set. -/
def IsPrimeWheelSmooth (S : Finset ℕ) (n : ℕ) : Prop :=
  Squarefree n ∧ ∀ p ∈ n.primeFactors, p ∈ S

/-- The sitewise smooth-core contribution.  The magnitude cut is fixed at the
right endpoint and is not mixed with the later moving prefix window. -/
def primeWheelSmoothCoreSite
    (S : Finset ℕ) (upper n : ℕ) : ℤ := by
  classical
  exact if n ≤ upper ∧ IsPrimeWheelSmooth S n then seededPrimeComb S n else 0

/-- Corrected site field: raw seed field minus twice the sites whose provisional
seed orientation is extraneous. -/
def correctedPrimeWheelSite
    (S : Finset ℕ) (upper n : ℕ) : ℤ :=
  seededPrimeComb S n - 2 * primeWheelSmoothCoreSite S upper n

/-- Finite data for one synchronized prime-wheel block. -/
structure PrimeWheelFiniteSystem where
  lower : ℕ
  upper : ℕ
  modulus : ℕ
  lower_lt_upper : lower < upper
  modulus_pos : 0 < modulus
  upper_lt_modulus : upper < modulus
  primeCoordinates : Finset ℕ
  primeCoordinates_prime : ∀ p ∈ primeCoordinates, Nat.Prime p

namespace PrimeWheelFiniteSystem

instance (W : PrimeWheelFiniteSystem) : NeZero W.modulus :=
  ⟨Nat.ne_of_gt W.modulus_pos⟩

/-- Raw site field associated to a finite wheel system. -/
def rawSite (W : PrimeWheelFiniteSystem) (n : ℕ) : ℤ :=
  seededPrimeComb W.primeCoordinates n

/-- Smooth-core site field associated to a finite wheel system. -/
def smoothCoreSite (W : PrimeWheelFiniteSystem) (n : ℕ) : ℤ :=
  primeWheelSmoothCoreSite W.primeCoordinates W.upper n

/-- Corrected site field associated to a finite wheel system. -/
def correctedSite (W : PrimeWheelFiniteSystem) (n : ℕ) : ℤ :=
  correctedPrimeWheelSite W.primeCoordinates W.upper n

/-- Integers in the pinned prefix `(lower,x]`. -/
def prefixInterval (W : PrimeWheelFiniteSystem) (x : ℕ) : Finset ℕ :=
  Finset.Ioc W.lower x

/-- Raw seeded mass in a pinned prefix. -/
def rawPrefix (W : PrimeWheelFiniteSystem) (x : ℕ) : ℤ :=
  ∑ n ∈ W.prefixInterval x, W.rawSite n

/-- Smooth-core mass in a pinned prefix. -/
def smoothCorePrefix (W : PrimeWheelFiniteSystem) (x : ℕ) : ℤ :=
  ∑ n ∈ W.prefixInterval x, W.smoothCoreSite n

/-- Joint residual in a pinned prefix. -/
def residual (W : PrimeWheelFiniteSystem) (x : ℕ) : ℤ :=
  W.rawPrefix x - 2 * W.smoothCorePrefix x

/-- A finite arithmetic certificate says that the exact sitewise correction is
Möbius throughout the block.  This is an ordinary structure carrying a theorem,
not an axiom. -/
structure ArithmeticCertificate (W : PrimeWheelFiniteSystem) : Prop where
  corrected_eq_moebius :
    ∀ n : ℕ, W.lower < n → n ≤ W.upper → W.correctedSite n = μ n

/-- The signed raw/core residual is exactly the sum of the corrected site field. -/
theorem residual_eq_corrected_sum
    (W : PrimeWheelFiniteSystem) (x : ℕ) :
    W.residual x = ∑ n ∈ W.prefixInterval x, W.correctedSite n := by
  classical
  unfold residual rawPrefix smoothCorePrefix correctedSite rawSite smoothCoreSite
    correctedPrimeWheelSite prefixInterval
  rw [Finset.mul_sum]
  rw [← Finset.sum_sub_distrib]

/-- A pointwise arithmetic certificate immediately yields the exact nested-prefix
Möbius identity. -/
theorem residual_eq_moebius_sum
    (W : PrimeWheelFiniteSystem)
    (cert : W.ArithmeticCertificate)
    {x : ℕ} (hx : x ≤ W.upper) :
    W.residual x = ∑ n ∈ W.prefixInterval x, μ n := by
  rw [W.residual_eq_corrected_sum]
  apply Finset.sum_congr rfl
  intro n hn
  have hmem := Finset.mem_Ioc.mp hn
  exact cert.corrected_eq_moebius n hmem.1 (hmem.2.trans hx)

/-- Complex-valued form of the exact nested-prefix identity. -/
theorem residual_cast_eq_moebius_sum
    (W : PrimeWheelFiniteSystem)
    (cert : W.ArithmeticCertificate)
    {x : ℕ} (hx : x ≤ W.upper) :
    ((W.residual x : ℤ) : ℂ) =
      ∑ n ∈ W.prefixInterval x, (((μ n : ℤ) : ℂ)) := by
  rw [W.residual_eq_moebius_sum cert hx]
  push_cast
  rfl

end PrimeWheelFiniteSystem

end RHLean.Arithmetic
