import Mathlib
import RHLean.Arithmetic.PrimeWheelFiniteSystem

open scoped BigOperators

noncomputable section

namespace RHLean.Analysis

open RHLean.Arithmetic

private theorem localPrimeComb_eq_indicators (p n : ℕ) :
    localPrimeComb p n =
      1 - 2 * (if p ∣ n then 1 else 0) +
        (if p ^ 2 ∣ n then 1 else 0) := by
  unfold localPrimeComb
  by_cases hsq : p ^ 2 ∣ n
  · have hp : p ∣ n := dvd_trans (dvd_pow_self p (by norm_num)) hsq
    simp [hsq, hp]
  · by_cases hp : p ∣ n
    · simp [hsq, hp]
    · simp [hsq, hp]

private theorem card_multiples_prime_below_square
    {p : ℕ} (hp : Nat.Prime p) :
    ((Finset.range (p ^ 2)).filter fun n => p ∣ n).card = p := by
  classical
  have hset :
      (Finset.range (p ^ 2)).filter (fun n => p ∣ n) =
        (Finset.range p).image (fun a => p * a) := by
    ext n
    simp only [Finset.mem_filter, Finset.mem_range, Finset.mem_image]
    constructor
    · rintro ⟨hnlt, hdvd⟩
      rcases hdvd with ⟨a, rfl⟩
      have ha : a < p := by
        nlinarith [hp.pos]
      exact ⟨a, ha, rfl⟩
    · rintro ⟨a, ha, rfl⟩
      constructor
      · nlinarith [hp.pos]
      · exact ⟨a, rfl⟩
  rw [hset]
  have hinj : Set.InjOn (fun a : ℕ => p * a) (Finset.range p : Set ℕ) := by
    intro a ha b hb hab
    exact Nat.eq_of_mul_eq_mul_left hp.pos hab
  rw [Finset.card_image_iff.mpr hinj, Finset.card_range]

private theorem card_square_multiples_below_square
    {p : ℕ} (hp : Nat.Prime p) :
    ((Finset.range (p ^ 2)).filter fun n => p ^ 2 ∣ n).card = 1 := by
  classical
  have hset :
      (Finset.range (p ^ 2)).filter (fun n => p ^ 2 ∣ n) = {0} := by
    ext n
    simp only [Finset.mem_filter, Finset.mem_range, Finset.mem_singleton]
    constructor
    · rintro ⟨hnlt, hdvd⟩
      by_contra hn0
      have hle := Nat.le_of_dvd (Nat.pos_of_ne_zero hn0) hdvd
      omega
    · intro hn
      subst n
      exact ⟨pow_pos hp.pos 2, dvd_zero _⟩
  simp [hset]

/-- Exact local constant-mode multiplier of one square-sensitive prime comb. -/
theorem localPrimeComb_complete_sum
    {p : ℕ} (hp : Nat.Prime p) :
    (∑ x : Fin (p ^ 2), localPrimeComb p x.val) =
      (((p - 1) ^ 2 : ℕ) : ℤ) := by
  have hpcount :
      (∑ n ∈ Finset.range (p ^ 2),
        if p ∣ n then (1 : ℤ) else 0) = (p : ℤ) := by
    rw [Finset.sum_boole]
    exact_mod_cast card_multiples_prime_below_square hp
  have hsqcount :
      (∑ n ∈ Finset.range (p ^ 2),
        if p ^ 2 ∣ n then (1 : ℤ) else 0) = 1 := by
    rw [Finset.sum_boole]
    exact_mod_cast card_square_multiples_below_square hp
  have htotal :
      (∑ _n ∈ Finset.range (p ^ 2), (1 : ℤ)) = ((p ^ 2 : ℕ) : ℤ) := by
    simp
  rw [Fin.sum_univ_eq_sum_range]
  calc
    (∑ n ∈ Finset.range (p ^ 2), localPrimeComb p n) =
        ∑ n ∈ Finset.range (p ^ 2),
          (1 - 2 * (if p ∣ n then 1 else 0) +
            (if p ^ 2 ∣ n then 1 else 0) : ℤ) := by
      apply Finset.sum_congr rfl
      intro n hn
      exact localPrimeComb_eq_indicators p n
    _ = (∑ _n ∈ Finset.range (p ^ 2), (1 : ℤ)) -
          2 * (∑ n ∈ Finset.range (p ^ 2),
            if p ∣ n then (1 : ℤ) else 0) +
          (∑ n ∈ Finset.range (p ^ 2),
            if p ^ 2 ∣ n then (1 : ℤ) else 0) := by
      rw [Finset.sum_add_distrib, Finset.sum_sub_distrib]
      rw [← Finset.mul_sum]
    _ = ((p ^ 2 : ℕ) : ℤ) - 2 * (p : ℤ) + 1 := by
      rw [htotal, hpcount, hsqcount]
    _ = (((p - 1) ^ 2 : ℕ) : ℤ) := by
      push_cast [Nat.cast_sub hp.one_le]
      ring

/-- Independent CRT-coordinate assignment for the complete square-sensitive
wheel generated by `S`. -/
abbrev PrimeWheelCRTPoint (S : Finset ℕ) :=
  ∀ p : {p // p ∈ S}, Fin (p.val ^ 2)

/-- Complete seeded state on the CRT coordinate product. -/
def primeWheelCRTState (S : Finset ℕ) (x : PrimeWheelCRTPoint S) : ℤ :=
  -∏ p : {p // p ∈ S}, localPrimeComb p.val (x p).val

/-- Complete signed mass over every CRT residue assignment. -/
def primeWheelCRTMass (S : Finset ℕ) : ℤ :=
  ∑ x : PrimeWheelCRTPoint S, primeWheelCRTState S x

/-- Exact separation of the complete CRT mass into its independent local sums. -/
theorem primeWheelCRTMass_eq_neg_prod_localSums (S : Finset ℕ) :
    primeWheelCRTMass S =
      -∏ p : {p // p ∈ S},
        ∑ x : Fin (p.val ^ 2), localPrimeComb p.val x.val := by
  classical
  unfold primeWheelCRTMass primeWheelCRTState
  rw [Finset.sum_neg_distrib]
  apply congrArg Neg.neg
  symm
  simpa using
    (Finset.prod_univ_sum
      (t := fun p : {p // p ∈ S} =>
        (Finset.univ : Finset (Fin (p.val ^ 2))))
      (f := fun p x => localPrimeComb p.val x.val))

/-- Exact complete-wheel product law. -/
theorem primeWheelCRTMass_eq_neg_prod_primeFactors
    (S : Finset ℕ)
    (hprime : ∀ p ∈ S, Nat.Prime p) :
    primeWheelCRTMass S =
      -∏ p : {p // p ∈ S}, (((p.val - 1) ^ 2 : ℕ) : ℤ) := by
  rw [primeWheelCRTMass_eq_neg_prod_localSums]
  apply congrArg Neg.neg
  apply Fintype.prod_congr
  intro p
  exact localPrimeComb_complete_sum (hprime p.val p.property)

private def localPrimeCombCRTAtom
    (p : ℕ) (hp : Nat.Prime p)
    (x s : Fin (p ^ 2)) : ℂ := by
  letI : NeZero (p ^ 2) := ⟨pow_ne_zero 2 hp.ne_zero⟩
  exact (((localPrimeComb p x.val : ℤ) : ℂ)) *
    ZMod.stdAddChar
      (-(((x.val : ℕ) : ZMod (p ^ 2)) *
        ((s.val : ℕ) : ZMod (p ^ 2))))

/-- Unnormalized local Fourier coefficient of one square-sensitive comb. -/
def localPrimeCombCRTSpectrum
    (p : ℕ) (hp : Nat.Prime p) (s : Fin (p ^ 2)) : ℂ :=
  ∑ x : Fin (p ^ 2), localPrimeCombCRTAtom p hp x s

/-- Complete Fourier transform on the independent CRT coordinate product. -/
def primeWheelCRTSpectrum
    (S : Finset ℕ)
    (hprime : ∀ p ∈ S, Nat.Prime p)
    (r : ∀ p : {p // p ∈ S}, Fin (p.val ^ 2)) : ℂ :=
  ∑ x : PrimeWheelCRTPoint S,
    -∏ p : {p // p ∈ S},
      localPrimeCombCRTAtom p.val (hprime p.val p.property) (x p) (r p)

/-- Exact tensor-product formula for the complete raw comb spectrum in CRT
coordinates. -/
theorem primeWheelCRTSpectrum_eq_neg_prod_local
    (S : Finset ℕ)
    (hprime : ∀ p ∈ S, Nat.Prime p)
    (r : ∀ p : {p // p ∈ S}, Fin (p.val ^ 2)) :
    primeWheelCRTSpectrum S hprime r =
      -∏ p : {p // p ∈ S},
        localPrimeCombCRTSpectrum p.val (hprime p.val p.property) (r p) := by
  classical
  unfold primeWheelCRTSpectrum localPrimeCombCRTSpectrum
  rw [Finset.sum_neg_distrib]
  apply congrArg Neg.neg
  symm
  simpa using
    (Finset.prod_univ_sum
      (t := fun p : {p // p ∈ S} =>
        (Finset.univ : Finset (Fin (p.val ^ 2))))
      (f := fun p x =>
        localPrimeCombCRTAtom p.val (hprime p.val p.property) x (r p)))

end RHLean.Analysis
